import os
import datetime
import json

output_dir = "analysis_results"
os.makedirs(output_dir, exist_ok=True)

timestamp = datetime.datetime.now().isoformat()
output_data = {
    "timestamp": timestamp,
    "runner_hostname": os.environ.get('HOSTNAME', 'unknown_host'),
    "repository": os.environ.get('GITHUB_REPOSITORY', 'unknown_repo'),
    "job_id": os.environ.get('GITHUB_JOB', 'unknown_job'),
    "message": "This data was generated by a custom Python script on a Kubernetes runner."
}

output_file_path = os.path.join(output_dir, f"report_{timestamp.replace(':', '-')}.json")
with open(output_file_path, 'w') as f:
    json.dump(output_data, f, indent=2)

print(f"Generated report: {output_file_path}")

# Simulate some processing
print("Performing some complex calculations...")
for i in range(5):
    print(f"Processing step {i+1}...")

print("Script finished successfully.")
