name: Print Organization Secret

on:
  push:
    branches:
      - main # This workflow will run on pushes to the 'main' branch
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print the Organization Secret
        run: |
          echo "The organization secret value is: ${{ vars.ORG_TEST_SECRET }}"
          # For security, secrets are masked in logs.
          # This means you'll see *** instead of the actual value.
          # This is expected and a good security practice!
          echo "Verify it was used: ${{ contains(secrets.ORG_TEST_SECRET, 'Hello') }}"
          # The 'contains' function might reveal if it's the correct secret,
          # but direct printing will always be masked.
